"""add_is_admin_fix_count_accepted

Revision ID: d619747370c1
Revises: f9260f7e454c
Create Date: 2026-07-12 19:35:08.256374
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd619747370c1'
down_revision: Union[str, None] = 'f9260f7e454c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_usage', 'count',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('cleaning_recommendations', 'accepted',
               existing_type=sa.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.alter_column('cleaning_recommendations', 'accepted',
               existing_type=sa.Boolean(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('api_usage', 'count',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
